diseases = {
    "Hypertension": "Sodium reduction, DASH diet",
    "Coronary Artery Disease": "Mediterranean diet, fiber, omega-3s",
    "Congestive Heart Failure": "Sodium and fluid restriction",
    "Hyperlipidemia": "Soluble fiber, plant sterols, low saturated fat",
    "Atherosclerosis": "Anti-inflammatory diet, plant-based fats",
    "Type 2 Diabetes": "Low-glycemic diet, carb management",
    "Type 1 Diabetes": "Carb counting, blood sugar regulation",
    "Metabolic Syndrome": "Weight loss, insulin sensitivity diet",
    "Obesity": "Caloric deficit, whole-food nutrition",
    "Peripheral Artery Disease": "Antioxidant-rich, low-cholesterol diet",
    "Stroke (Post)": "DASH/Mediterranean diet, reduce saturated fat",
    "Insulin Resistance": "Low-carb, high-fiber diet",
    "Prediabetes": "Weight management, whole grains",
    "Arrhythmias": "Electrolyte balance: potassium, magnesium",
    "Post-Heart Attack Recovery": "Cardioprotective diet, low sodium",
    "Hypothyroidism": "Iodine, selenium, avoid goitrogens",
    "Hyperthyroidism": "Energy support, calcium/vitamin D",
    "PCOS": "Low-GI diet, reduce refined carbs",
    "Cushing's Syndrome": "High protein, manage blood sugar",
    "Addison's Disease": "Adequate sodium, electrolyte balance",
    "Pituitary Disorders": "Support hormone balance via whole foods",
    "Adrenal Fatigue": "Controversial, focus on balanced nutrition",
    "Insulinoma": "Frequent small meals, carb regulation",
    "Diabetes Insipidus": "Hydration, electrolyte management",
    "Hormonal Imbalances": "Plant-based hormones, fat balance",
    "GERD": "Avoid trigger foods, eat smaller meals",
    "IBS": "Low FODMAP diet, soluble fiber",
    "Crohn's Disease": "Anti-inflammatory, low-residue diet during flare-ups",
    "Ulcerative Colitis": "Anti-inflammatory diet, manage fiber based on symptoms",
    "Celiac Disease": "Strict gluten-free diet",
    "NAFLD": "Low-sugar, high-fiber, weight loss diet",
    "Alcoholic Liver Disease": "Eliminate alcohol, nutrient-dense support",
    "Cirrhosis": "Low sodium, high-protein as tolerated",
    "Gallbladder Disease": "Low-fat, smaller meals",
    "Chronic Pancreatitis": "Low-fat, enzyme supplementation",
    "Constipation": "High-fiber diet, hydration",
    "Peptic Ulcers": "Avoid NSAIDs, acidic/spicy foods",
    "Diverticular Disease": "High-fiber diet, manage inflammation",
    "Bile Acid Malabsorption": "Low-fat, bile acid binders",
    "SIBO": "Low FODMAP or elemental diet",
    "Chronic Kidney Disease": "Low sodium, phosphorus, protein control",
    "Kidney Stones": "Hydration, oxalate and sodium control",
    "Polycystic Kidney Disease": "Manage sodium, fluids, plant-based diet",
    "Gout": "Low-purine, avoid alcohol and fructose",
    "Nephrotic Syndrome": "Sodium restriction, protein balance",
    "Urinary Incontinence": "Avoid bladder irritants like caffeine, spicy foods",
    "Interstitial Cystitis": "Low-acid, bladder-safe diet",
    "Electrolyte Imbalances": "Adjust diet for sodium, potassium, calcium",
    "Hyperoxaluria": "Limit oxalate-rich foods",
    "Recurrent UTIs": "Hydration, cranberry, avoid sugar excess",
    "Osteoarthritis": "Weight control, anti-inflammatory diet",
    "Rheumatoid Arthritis": "Omega-3s, Mediterranean/anti-inflammatory diet",
    "Lupus": "Anti-inflammatory, vitamin D and calcium support",
    "Psoriatic Arthritis": "Anti-inflammatory, weight management",
    "Osteoporosis": "Calcium, vitamin D, protein, limit soda",
    "Fibromyalgia": "Whole-foods, avoid additives/sugar",
    "Sarcopenia": "High-quality protein, resistance training",
    "Chronic Low Back Pain": "Reduce inflammation, weight support",
    "Gouty Arthritis": "Low purine, reduce red meat and alcohol",
    "Tendinopathies": "Collagen, vitamin C, anti-inflammatory diet",
    "Alzheimer's Disease": "MIND or Mediterranean diet, antioxidants",
    "Parkinson's Disease": "Timing of protein with meds, fiber",
    "ALS": "High-calorie, nutrient-dense support",
    "Multiple Sclerosis": "Anti-inflammatory, vitamin D, omega-3s",
    "Epilepsy": "Ketogenic diet in refractory cases",
    "Migraine": "Avoid food triggers, magnesium, hydration",
    "Neuropathy": "B vitamins, blood sugar control",
    "Post-Stroke Cognitive Impairment": "Brain-healthy fats, antioxidant nutrients",
    "Huntington's Disease": "High-calorie, supportive nutrition",
    "Essential Tremor": "Balanced nutrition, avoid stimulants",
    "Iron-Deficiency Anemia": "Iron-rich foods, vitamin C",
    "Vitamin B12 Deficiency": "Animal-based foods or fortified foods",
    "Folate Deficiency Anemia": "Leafy greens, legumes, fortified grains",
    "Sickle Cell Disease": "Folate, hydration, antioxidant support",
    "Thalassemia": "Avoid excess iron unless deficient, folate support",
    "Autoimmune Hepatitis": "Liver-supportive, anti-inflammatory diet",
    "HIV/AIDS": "Immune-supporting, high-protein nutrient-dense",
    "Chronic Fatigue Syndrome": "Manage food sensitivities, steady energy foods",
    "Mast Cell Activation Syndrome": "Low histamine diet",
    "Systemic Inflammation": "Anti-inflammatory, whole foods diet",
    "Psoriasis": "Anti-inflammatory diet, gluten-free in some cases",
    "Eczema": "Identify food triggers, hydration, omega-3s",
    "Acne": "Low-glycemic, anti-inflammatory, reduce dairy",
    "Rosacea": "Avoid spicy foods, alcohol, and temperature extremes",
    "Vitiligo": "Antioxidants, B12 and folate support",
    "Macular Degeneration": "Lutein, zeaxanthin, omega-3s",
    "Glaucoma": "Weight management, antioxidant support",
    "Dry Eye Syndrome": "Hydration, omega-3s",
    "Periodontal Disease": "Vitamin C, avoid high sugar",
    "Oral Lichen Planus": "Avoid acidic/spicy foods, nutrient support",
    "Colorectal Cancer": "High fiber, low red/processed meat",
    "Breast Cancer": "Weight control, plant-based diet",
    "Prostate Cancer": "Lycopene, anti-inflammatory diet",
    "Stomach Cancer": "Avoid processed meats, high salt foods",
    "Esophageal Cancer": "Avoid reflux triggers, soft foods",
    "Liver Cancer": "Reduce alcohol, plant-based supportive diet",
    "Pancreatic Cancer": "High-calorie, enzyme supplementation",
    "Ovarian Cancer": "Antioxidant-rich, weight control",
    "Endometrial Cancer": "Low sugar, weight management",
    "Kidney Cancer": "Low sodium, plant-based, hydration"
}
  